title: "Christian Aguirre"
description: "Data Analyst Portfolio"
baseurl: "" 
url: "https://caguirre1378.github.io"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /:collection/:name

