title: Christian Aguirre
name: Christian Aguirre
description: Data Analyst Portfolio
url: "https://caguirre1378.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Christian Aguirre"
  avatar: "/assets/images/headshot.jpg"
  bio: "Curious analyst focused on turning data into decisions."

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: false

include:
  - _pages
