title: "Christian Aguirre"
description: "Data & ML portfolio"
url: "https://caguirre1378.github.io"
baseurl: "/Data-Analyst-Portfolio"

remote_theme: "mmistakes/minimal-mistakes"
fontawesome: true

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

# Include custom pages
include:
  - _pages

# Projects collection
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults for project pages
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false

# Top navigation
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /projects/
  - title: "Resume"
    url: /resume/
