title: Christian J. Aguirre
logo: /assets/Professional Photo.png
# description: "text below image"
show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: pages-themes/slate@latest [1, 3, 7]
plugins:

  - jekyll-remote-theme [1, 7, 8]
