title: "Christian Aguirre"
description: "Data Analyst Portfolio"
baseurl: "" 
url: "https://caguirre1378.github.io"

remote_theme: "mmistakes/minimal-mistakes"
fontawesome: true          # ← required for the icon set
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag


collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false


# Top navigation menu
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/
  - title: "Resume"
    url: /resume/

