title: "Christian Aguirre"
description: "Data Analyst Portfolio"
baseurl: "" 
url: "https://caguirre1378.github.io"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"   # optional, you can try "air", "contrast", etc.
fontawesome: true                  # ✅ enables icon packs

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

collections:
  projects:
    output: true
    permalink: /:collection/:name

# Navigation bar
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: single

# Top navigation menu
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/
  - title: "Resume"
    url: /resume/

